import { readFile } from 'node:fs/promises'
import { test } from 'node:test'
import assert from 'node:assert/strict'

const ROOT = new URL('../', import.meta.url)

async function readProjectFile(path) {
  return readFile(new URL(path, ROOT), 'utf8')
}

async function readOptionalProjectFile(path) {
  try {
    return await readProjectFile(path)
  } catch {
    return ''
  }
}

test('phone capture starts from one entry and exposes the required live data wall', async () => {
  const statusBar = await readProjectFile('frontend/src/components/SessionStatusBar.vue')
  const liveDashboard = await readProjectFile('frontend/src/pages/LiveDashboard.vue')
  const observationDashboard = await readProjectFile('frontend/src/pages/ObservationDashboard.vue')
  const appTopNav = await readProjectFile('frontend/src/components/AppTopNav.vue')
  const router = await readProjectFile('frontend/src/router.ts')
  const productLibraryPanel = await readProjectFile('frontend/src/components/ProductLibraryPanel.vue')
  const frameGalleryPanel = await readProjectFile('frontend/src/components/FrameGalleryPanel.vue')
  const transcriptPanel = await readProjectFile('frontend/src/components/TranscriptPanel.vue')
  const liveSourcePanel = await readProjectFile('frontend/src/components/LiveSourcePanel.vue')
  const scrcpyPanel = await readProjectFile('frontend/src/components/ScrcpyPanel.vue')
  const store = await readProjectFile('frontend/src/stores/jlao.ts')
  const apiJlao = await readProjectFile('frontend/src/api/jlao.ts')
  const schemas = await readProjectFile('backend/app/schemas.py')
  const phoneCaptureService = await readProjectFile('backend/app/services/phone_capture_service.py')
  const frameService = await readProjectFile('backend/app/services/frame_service.py')
  const liveCommentService = await readOptionalProjectFile('backend/app/services/live_comment_service.py')
  const scrcpyService = await readProjectFile('backend/app/services/scrcpy_service.py')
  const nativeSttService = await readOptionalProjectFile('backend/app/services/native_stt_service.py')
  const sttWs = await readProjectFile('backend/app/ws/stt_ws.py')
  const customersApi = await readProjectFile('backend/app/api/customers.py')
  const backendRequirements = await readProjectFile('backend/requirements.txt')
  const backendMain = await readProjectFile('backend/app/main.py')
  const apiClient = await readProjectFile('frontend/src/api/client.ts')
  const globalCss = await readProjectFile('frontend/src/styles/global.css')
  const startBackendScript = await readProjectFile('scripts/start-backend.ps1')

  assert.match(router, /ObservationDashboard/)
  assert.match(router, /path: '\/observe'/)
  assert.match(appTopNav, /to="\/live"/)
  assert.match(appTopNav, /to="\/observe"/)

  assert.match(statusBar, /startButtonLabel = computed/)
  assert.match(statusBar, /sourceActive\?: boolean/)
  assert.match(statusBar, /needsVideoSource/)
  assert.doesNotMatch(statusBar, /NSelect/)

  assert.match(liveDashboard, /ref="yoloLivePanel"/)
  assert.match(liveDashboard, /store\.activeCaptureMode === 'own'/)
  assert.match(liveDashboard, /startScrcpySession\(\)/)
  assert.match(liveDashboard, /startPhoneCaptureSession\(\)/)
  assert.match(liveDashboard, /store\.startNativeSttSession\(\)/)
  assert.match(liveDashboard, /refreshPhoneCaptureStatus\(\)/)
  assert.match(liveDashboard, /:comment-events="store\.liveComments"/)
  assert.match(liveDashboard, /frame-gallery-panel/)
  assert.match(liveDashboard, /product-library-panel/)
  assert.equal(liveDashboard.includes('liveSourcePanel.value?.startProjectedAudioCapture()'), false)
  assert.equal(liveDashboard.includes('startAudioInputCapture()'), false)

  assert.match(observationDashboard, /<jade-yolo-live-panel/)
  assert.match(observationDashboard, /store\.activeCaptureMode === 'observe'/)
  assert.match(observationDashboard, /await store\.startScrcpySession\(\)/)
  assert.match(observationDashboard, /await store\.startPhoneCaptureSession\(\)/)
  assert.match(observationDashboard, /await store\.refreshPhoneCaptureStatus\(\)/)
  assert.match(observationDashboard, /store\.stopNativeSttSession\(\)/)
  assert.match(observationDashboard, /sale-card-panel/)
  assert.match(observationDashboard, /:comment-events="store\.liveComments"/)
  assert.equal(observationDashboard.includes('startProjectedAudioCapture()'), false)

  assert.match(liveSourcePanel, /startProjectedAudioCapture/)
  assert.match(liveSourcePanel, /navigator\.mediaDevices\.getDisplayMedia/)
  assert.match(liveSourcePanel, /systemAudio: 'exclude'/)
  assert.match(liveSourcePanel, /emit\('startStt'\)[\s\S]*await startAudioStreaming\(stream\.value\)/)
  assert.doesNotMatch(liveSourcePanel, /projectedAudioStream\.value && audioActive\.value[\s\S]*startAudioStreaming/)

  assert.match(transcriptPanel, /commentEvents: VirtualCustomerEvent\[\]/)
  assert.match(transcriptPanel, /orderedComments/)
  assert.match(transcriptPanel, /transcript-split-grid/)
  assert.match(frameGalleryPanel, /const collapsed = ref\(true\)/)
  assert.match(frameGalleryPanel, /v-if="!collapsed"/)
  assert.match(productLibraryPanel, /products/)
  assert.equal(scrcpyPanel.includes('startScrcpySession'), false)

  assert.match(store, /interval_seconds: 0\.2/)
  assert.match(store, /liveComments: VirtualCustomerEvent\[\]/)
  assert.match(store, /fetchLiveComments/)
  assert.match(store, /nativeSttInfo/)
  assert.match(store, /startNativeSttSession/)
  assert.match(store, /stopNativeSttSession/)
  assert.match(store, /cleanLiveRoomNameForDisplay/)
  assert.match(store, /liveRoomNameLabel/)
  assert.match(store, /WebSocket\.CONNECTING/)
  assert.match(store, /pendingSttFrames/)

  assert.match(apiJlao, /startNativeStt/)
  assert.match(apiJlao, /stopNativeStt/)
  assert.match(apiJlao, /getNativeSttStatus/)
  assert.match(apiJlao, /fetchLiveComments/)

  assert.match(schemas, /ge=0\.2/)
  assert.match(schemas, /interval_seconds: float = Field\(default=0\.2/)
  assert.match(schemas, /class ScrcpyStartRequest\(BaseModel\):[\s\S]*serial: str = ""/)
  assert.match(schemas, /max_size: int = Field\(default=1024/)

  assert.match(apiClient, /resolveApiBase/)
  assert.match(apiClient, /productionShell: isProductionShell/)
  assert.match(apiClient, /window\.location\.origin/)
  assert.match(backendMain, /Access-Control-Allow-Private-Network/)
  assert.match(backendMain, /load_dotenv/)
  assert.match(backendMain, /WORKSPACE_DIR \/ '.env'/)
  assert.match(backendMain, /native_stt_router/)

  assert.match(globalCss, /\.data-panel-transcript \{[\s\S]*grid-column: 1 \/ -1;/)
  assert.match(globalCss, /\.one-screen-dashboard \{[\s\S]*overflow: auto;/)
  assert.match(globalCss, /\.projection-stage \{[\s\S]*width: 360px;[\s\S]*height: 270px;/)

  assert.match(startBackendScript, /\.venv-local\\Scripts\\python\.exe/)

  assert.match(sttWs, /LocalChunkStt/)
  assert.match(sttWs, /STT_PROVIDER = "local"/)
  assert.doesNotMatch(sttWs, /AliyunRealtimeStt/)
  assert.match(sttWs, /manager\.broadcast\(session_id, "transcript_segment"/)

  assert.match(frameService, /process_live_comments_from_frame/)
  assert.match(frameService, /asyncio\.create_task/)
  assert.match(liveCommentService, /PaddleOCR/)
  assert.match(liveCommentService, /_recognize_with_tesseract/)
  assert.doesNotMatch(liveCommentService, /_recognize_with_windows_ocr/)
  assert.doesNotMatch(liveCommentService, /Windows OCR/)
  assert.doesNotMatch(liveCommentService, /RecognizeGeneral/)
  assert.doesNotMatch(liveCommentService, /ocr-api\.cn-hangzhou\.aliyuncs\.com/)
  assert.match(liveCommentService, /events_from_ocr_lines/)
  assert.match(customersApi, /live-comments/)
  assert.match(customersApi, /live-comments\/status/)

  assert.match(nativeSttService, /--no-video/)
  assert.match(nativeSttService, /--no-window/)
  assert.match(nativeSttService, /_NATIVE_STT_AUDIO_SOURCE = os\.getenv\("NATIVE_STT_AUDIO_SOURCE", "playback"\)/)
  assert.match(nativeSttService, /--audio-source=\{_NATIVE_STT_AUDIO_SOURCE\}/)
  assert.match(nativeSttService, /_stream_recorded_wav/)
  assert.match(nativeSttService, /LocalChunkStt/)
  assert.doesNotMatch(nativeSttService, /AliyunRealtimeStt/)
  assert.doesNotMatch(backendRequirements, /aliyun-python-sdk-core/)

  assert.match(phoneCaptureService, /image\.convert\("RGB"\)/)
  assert.doesNotMatch(phoneCaptureService, /image\.thumbnail/)
  assert.match(phoneCaptureService, /QtScrcpy-dev/)
  assert.match(scrcpyService, /SCRCPY_MAX_SIZE = 1080/)
  assert.match(scrcpyService, /effective_max_size = SCRCPY_MAX_SIZE/)
  assert.match(scrcpyService, /--audio-source=playback/)
  assert.match(scrcpyService, /_scrcpy_supervisor/)
  assert.match(scrcpyService, /reconnect_attempts/)
  assert.match(scrcpyService, /_recover_scrcpy_before_retry/)
  assert.doesNotMatch(scrcpyService, /--no-audio/)
  assert.doesNotMatch(scrcpyService, /--audio-source=mic/)
  assert.match(scrcpyService, /--jlao-usb-connect/)
})
