import { readFile } from 'node:fs/promises'
import { test } from 'node:test'
import assert from 'node:assert/strict'

const ROOT = new URL('../', import.meta.url)

async function readProjectFile(path) {
  return readFile(new URL(path, ROOT), 'utf8')
}

async function readOptionalProjectFile(path) {
  try {
    return await readProjectFile(path)
  } catch (error) {
    return ''
  }
}

test('phone capture starts from one entry and exposes the required live data wall', async () => {
  const statusBar = await readProjectFile('frontend/src/components/SessionStatusBar.vue')
  const liveDashboard = await readProjectFile('frontend/src/pages/LiveDashboard.vue')
  const observationDashboard = await readOptionalProjectFile('frontend/src/pages/ObservationDashboard.vue')
  const appTopNav = await readProjectFile('frontend/src/components/AppTopNav.vue')
  const router = await readProjectFile('frontend/src/router.ts')
  const productLibraryPanel = await readProjectFile('frontend/src/components/ProductLibraryPanel.vue')
  const frameGalleryPanel = await readProjectFile('frontend/src/components/FrameGalleryPanel.vue')
  const transcriptPanel = await readProjectFile('frontend/src/components/TranscriptPanel.vue')
  const liveSourcePanel = await readProjectFile('frontend/src/components/LiveSourcePanel.vue')
  const scrcpyPanel = await readProjectFile('frontend/src/components/ScrcpyPanel.vue')
  const store = await readProjectFile('frontend/src/stores/jlao.ts')
  const apiJlao = await readProjectFile('frontend/src/api/jlao.ts')
  const schemas = await readProjectFile('backend/app/schemas.py')
  const phoneCaptureService = await readProjectFile('backend/app/services/phone_capture_service.py')
  const frameService = await readProjectFile('backend/app/services/frame_service.py')
  const liveCommentService = await readOptionalProjectFile('backend/app/services/live_comment_service.py')
  const scrcpyService = await readProjectFile('backend/app/services/scrcpy_service.py')
  const nativeSttService = await readOptionalProjectFile('backend/app/services/native_stt_service.py')
  const sttWs = await readProjectFile('backend/app/ws/stt_ws.py')
  const customersApi = await readProjectFile('backend/app/api/customers.py')
  const backendRequirements = await readProjectFile('backend/requirements.txt')
  const backendMain = await readProjectFile('backend/app/main.py')
  const apiClient = await readProjectFile('frontend/src/api/client.ts')
  const globalCss = await readProjectFile('frontend/src/styles/global.css')
  const startBackendScript = await readProjectFile('scripts/start-backend.ps1')
  const productsSample = await readProjectFile('data/samples/products.json')
  const customersSample = await readProjectFile('data/samples/virtual_customers.json')

  assert.equal(statusBar.includes('载入标签页'), false)
  assert.equal(statusBar.includes('载入手机端'), false)
  assert.equal(statusBar.includes('采集'), true)
  assert.equal(statusBar.includes('停止采集'), true)
  assert.equal(statusBar.includes('开始手机采集'), false)
  assert.equal(statusBar.includes('停止视频流'), false)
  assert.equal(statusBar.includes('黑盒观察'), true)
  assert.equal(statusBar.includes('音频未接入'), true)
  assert.equal(statusBar.includes('NSelect'), false)

  assert.match(router, /ObservationDashboard/)
  assert.match(router, /path: '\/observe'/)
  assert.match(appTopNav, /自有运营/)
  assert.match(appTopNav, /其它分析/)
  assert.match(liveDashboard, /自有直播间运营/)
  assert.match(liveDashboard, /手机投屏 · 实时转写 · 运营数据墙/)
  assert.equal(liveDashboard.includes('3AF9K24227080668'), false)
  assert.equal(observationDashboard.includes('3AF9K24227080668'), false)
  assert.match(liveDashboard, /startScrcpySession\(\)/)
  assert.match(liveDashboard, /startPhoneCaptureSession\(\)/)
  assert.match(observationDashboard, /其它直播间分析/)
  assert.match(observationDashboard, /黑盒观察 · 成交卡片 · 弹幕累积/)
  assert.match(observationDashboard, /sale-card-panel/)
  assert.match(observationDashboard, /成交卡片/)
  assert.match(observationDashboard, /卖家/)
  assert.match(observationDashboard, /买家/)
  assert.match(observationDashboard, /货品/)
  assert.match(observationDashboard, /价格/)
  assert.match(observationDashboard, /复盘骨架/)
  assert.match(observationDashboard, /讲了多少件货/)
  assert.match(observationDashboard, /哪些货卖了/)
  assert.match(observationDashboard, /每个客人发言累计/)
  assert.match(observationDashboard, /transcript-panel/)
  assert.match(observationDashboard, /frame-gallery-panel/)
  assert.match(observationDashboard, /product-library-panel/)

  assert.equal(liveDashboard.includes('@load-tab'), false)
  assert.equal(liveDashboard.includes('手机实时投屏'), false)
  assert.equal(liveDashboard.includes('scrcpy 原生窗口会在电脑桌面弹出'), false)
  assert.equal(scrcpyPanel.includes('启动投屏窗口'), false)
  assert.equal(scrcpyPanel.includes('开始 1秒截屏'), false)

  assert.equal(productsSample.includes('冰飘花手镯'), false)
  assert.equal(productsSample.includes('晴水手镯'), false)
  assert.equal(productsSample.includes('"category": "手镯"'), false)
  assert.equal(customersSample.includes('冰飘花手镯'), false)
  assert.equal(customersSample.includes('"手镯"'), false)

  assert.match(liveSourcePanel, /startProjectedAudioCapture/)
  assert.match(liveSourcePanel, /navigator\.mediaDevices\.getDisplayMedia/)
  assert.match(liveSourcePanel, /systemAudio: 'include'/)
  assert.match(liveSourcePanel, /projectedAudioStream\.value && audioActive\.value[\s\S]*await startAudioStreaming\(projectedAudioStream\.value\)[\s\S]*emit\('startStt'\)/)
  assert.match(liveSourcePanel, /await startAudioStreaming\(mediaStream\)[\s\S]*emit\('startStt'\)/)
  assert.equal(liveDashboard.includes('liveSourcePanel.value?.startProjectedAudioCapture()'), false)
  assert.equal(observationDashboard.includes('startProjectedAudioCapture()'), false)
  assert.match(liveDashboard, /store\.startNativeSttSession\(\)/)
  assert.match(observationDashboard, /store\.startNativeSttSession\(\)/)
  assert.equal(liveDashboard.includes('startAudioInputCapture()'), false)
  assert.equal(liveDashboard.includes('if (audioStarted) store.connectStt()'), false)
  assert.doesNotMatch(liveDashboard, /if \(phoneCaptureReady\) store\.connectStt\(\)[\s\S]*const audioStarted/)
  assert.match(liveDashboard, /refreshPhoneCaptureStatus\(\)/)
  assert.match(liveDashboard, /:comment-events="store\.liveComments"/)
  assert.equal(liveDashboard.includes(':comment-events="store.customerEvents"'), false)
  assert.match(observationDashboard, /:comment-events="store\.liveComments"/)
  assert.equal(observationDashboard.includes(':comment-events="store.customerEvents"'), false)
  assert.match(liveDashboard, /frame-gallery-panel/)
  assert.match(liveDashboard, /product-library-panel/)
  assert.match(transcriptPanel, /主播语言/)
  assert.match(transcriptPanel, /弹幕累积/)
  assert.match(transcriptPanel, /commentEvents: VirtualCustomerEvent\[\]/)
  assert.match(transcriptPanel, /orderedComments/)
  assert.match(transcriptPanel, /transcript-split-grid/)
  assert.match(globalCss, /\.data-panel-transcript \{[\s\S]*grid-column: 1 \/ -1;/)
  assert.match(globalCss, /\.one-screen-dashboard \{[\s\S]*overflow: auto;/)
  assert.match(globalCss, /\.ops-data-wall \{[\s\S]*grid-template-rows: minmax\(86px, auto\) minmax\(300px, 1\.55fr\) minmax\(145px, 0\.72fr\) minmax\(145px, 0\.72fr\);/)
  assert.match(globalCss, /\.ops-data-wall \.data-panel-transcript \{[\s\S]*min-height: 300px;/)
  assert.match(globalCss, /\.data-panel-transcript \.transcript-split-grid \{[\s\S]*height: 100%;/)
  assert.match(frameGalleryPanel, /const collapsed = ref\(true\)/)
  assert.match(frameGalleryPanel, /v-if="!collapsed"/)
  assert.match(frameGalleryPanel, /@click="toggleCollapsed"/)
  assert.match(frameGalleryPanel, /frame-gallery-panel" :class="\{ 'is-collapsed': collapsed \}"/)
  assert.match(globalCss, /\.frame-gallery-panel\.is-collapsed \{[\s\S]*align-self: start;/)
  assert.match(globalCss, /\.frame-gallery-panel\.is-collapsed \.frame-gallery-body \{[\s\S]*display: none;/)
  assert.match(productLibraryPanel, /商品库/)
  assert.match(appTopNav, /知识库/)
  assert.match(appTopNav, /客户库/)
  assert.match(appTopNav, /运营库/)
  assert.match(store, /interval_seconds: 0\.2/)
  assert.equal(store.includes('chunk_seconds: 3'), false)
  assert.match(store, /liveComments: VirtualCustomerEvent\[\]/)
  assert.match(store, /liveComments: \[\]/)
  assert.match(store, /fetchLiveComments/)
  assert.doesNotMatch(store, /message\.event === 'virtual_customer_event'[\s\S]{0,260}this\.liveComments/)
  assert.doesNotMatch(store, /this\.liveComments = customerEvents/)
  assert.match(store, /nativeSttInfo/)
  assert.match(store, /startNativeSttSession/)
  assert.match(store, /stopNativeSttSession/)
  assert.match(apiJlao, /startNativeStt/)
  assert.match(apiJlao, /stopNativeStt/)
  assert.match(apiJlao, /getNativeSttStatus/)
  assert.match(apiJlao, /fetchLiveComments/)
  assert.match(store, /message\.event === 'transcript_segment'/)
  assert.match(store, /WebSocket\.CONNECTING/)
  assert.match(store, /pendingSttFrames/)
  assert.match(store, /sendSttAudio\(frame: ArrayBuffer\)[\s\S]*this\.connectStt\(\)/)
  assert.match(schemas, /ge=0\.2/)
  assert.match(schemas, /interval_seconds: float = Field\(default=0\.2/)
  assert.match(schemas, /class ScrcpyStartRequest\(BaseModel\):[\s\S]*serial: str = ""/)
  assert.equal(schemas.includes('default=1080'), false)
  assert.match(schemas, /max_size: int = Field\(default=1024/)
  assert.equal(apiClient.includes('isProductionShell ? defaultApiBase'), false)
  assert.match(apiClient, /isProductionShell \? savedApiBase \|\| defaultApiBase/)
  assert.match(apiClient, /window\.location\.origin/)
  assert.match(backendMain, /Access-Control-Allow-Private-Network/)
  assert.equal(globalCss.includes('grid-template-columns: 280px minmax(720px, 1fr)'), false)
  assert.match(globalCss, /grid-template-columns: 360px minmax\(720px, 1fr\)/)
  assert.match(globalCss, /\.projection-stage \{[\s\S]*width: 360px;[\s\S]*height: 270px;/)
  assert.match(startBackendScript, /\.venv-local\\Scripts\\python\.exe/)
  assert.match(backendMain, /load_dotenv/)
  assert.match(backendMain, /WORKSPACE_DIR \/ '.env'/)
  assert.match(sttWs, /LocalChunkStt/)
  assert.match(sttWs, /STT_PROVIDER = "local"/)
  assert.doesNotMatch(sttWs, /AliyunRealtimeStt/)
  assert.match(sttWs, /\[stt .*\] connected/)
  assert.match(sttWs, /audio_chunks/)
  assert.match(sttWs, /manager\.broadcast\(session_id, "transcript_segment"/)
  assert.match(frameService, /process_live_comments_from_frame/)
  assert.match(frameService, /asyncio\.create_task/)
  assert.match(liveCommentService, /PaddleOCR/)
  assert.match(liveCommentService, /_recognize_with_tesseract/)
  assert.doesNotMatch(liveCommentService, /_recognize_with_windows_ocr/)
  assert.doesNotMatch(liveCommentService, /Windows OCR/)
  assert.doesNotMatch(liveCommentService, /RecognizeGeneral/)
  assert.doesNotMatch(liveCommentService, /ocr-api\.cn-hangzhou\.aliyuncs\.com/)
  assert.match(liveCommentService, /events_from_ocr_lines/)
  assert.match(customersApi, /live-comments/)
  assert.match(customersApi, /live-comments\/status/)
  assert.match(nativeSttService, /--no-video/)
  assert.match(nativeSttService, /--no-window/)
  assert.match(nativeSttService, /--audio-source=voice-performance/)
  assert.doesNotMatch(nativeSttService, /--audio-dup/)
  assert.match(nativeSttService, /_stream_recorded_wav/)
  assert.match(nativeSttService, /_find_wav_data_offset/)
  assert.doesNotMatch(nativeSttService, /--audio-source=mic/)
  assert.doesNotMatch(nativeSttService, /--audio-source=playback/)
  assert.doesNotMatch(nativeSttService, /--audio-source=output/)
  assert.doesNotMatch(nativeSttService, /--time-limit/)
  assert.match(nativeSttService, /--record-format/)
  assert.match(nativeSttService, /LocalChunkStt/)
  assert.doesNotMatch(nativeSttService, /AliyunRealtimeStt/)
  assert.match(nativeSttService, /_stop_native_stt_tasks_for_device/)
  assert.match(backendMain, /native_stt_router/)
  assert.doesNotMatch(backendRequirements, /aliyun-python-sdk-core/)
  assert.match(backendMain, /https:\/\/jlao\.szkakayiduo\.com/)
  assert.match(phoneCaptureService, /image\.thumbnail\(\(1024, 1024\)/)
  assert.equal(phoneCaptureService.includes('image.thumbnail((576, 1024)'), false)
  assert.match(scrcpyService, /SCRCPY_MAX_SIZE = 1024/)
  assert.match(scrcpyService, /effective_max_size = SCRCPY_MAX_SIZE/)
  assert.match(scrcpyService, /--audio-source=playback/)
  assert.doesNotMatch(scrcpyService, /--no-audio/)
  assert.doesNotMatch(scrcpyService, /--audio-source=mic/)
  assert.doesNotMatch(scrcpyService, /--audio-source=voice-performance/)
  assert.match(phoneCaptureService, /QtScrcpy-dev/)
  assert.match(scrcpyService, /--jlao-usb-connect/)
  assert.match(scrcpyService, /QtScrcpy-dev/)
})

