import fs from 'node:fs'

const source = fs.readFileSync('frontend/src/pages/ObservationDashboard.vue', 'utf8')
const yoloPanelSource = fs.readFileSync('frontend/src/components/JadeYoloLivePanel.vue', 'utf8')
const liveSourcePanelSource = fs.readFileSync('frontend/src/components/LiveSourcePanel.vue', 'utf8')
const statusBarSource = fs.readFileSync('frontend/src/components/SessionStatusBar.vue', 'utf8')
const storeSource = fs.readFileSync('frontend/src/stores/jlao.ts', 'utf8')
const settingsSource = fs.readFileSync('frontend/src/components/SettingsPanel.vue', 'utf8')

function assertIncludes(text: string, expected: string) {
  if (!text.includes(expected)) {
    throw new Error(`Expected source to include ${expected}`)
  }
}

function assertNotIncludes(text: string, unexpected: string) {
  if (text.includes(unexpected)) {
    throw new Error(`Expected source not to include ${unexpected}`)
  }
}

assertIncludes(source, '<jade-yolo-live-panel')
assertIncludes(source, 'ref="yoloLivePanel"')
assertIncludes(source, ':source-active="observeSourceActive"')
assertIncludes(source, '@capture-state-change="handleYoloCaptureStateChange"')
assertIncludes(source, ':stopping="observeProjectionStopping"')
assertIncludes(source, ':video-loading="observeVideoLoading"')
assertIncludes(source, ':ocr-loading="observeOcrLoading"')
assertIncludes(source, ':ocr-runtime-loading="store.frameAnalyzing"')
assertIncludes(source, ':native-audio-loading="store.nativeAudioLoading"')
assertIncludes(source, ':stt-loading="store.nativeSttLoading"')
assertIncludes(source, ':recording-loading="store.recorderLoading"')
assertIncludes(source, ':projection-active="observeProjectionActive"')
assertIncludes(source, ':video-active="observeCaptureActive"')
assertIncludes(source, ':native-audio-active="Boolean(store.nativeAudioInfo?.running)"')
assertIncludes(source, ':stt-active="Boolean(store.nativeSttInfo?.running)"')
assertIncludes(source, ':ocr-active="observeOcrActive"')
assertIncludes(source, ':recording-active="observeRecordingActive"')
assertIncludes(source, '@toggle-projection="toggleProjection"')
assertIncludes(source, '@toggle-video="toggleVideo"')
assertIncludes(source, '@toggle-audio="toggleAudio"')
assertIncludes(source, '@toggle-stt="toggleStt"')
assertIncludes(source, '@toggle-ocr="toggleOcr"')
assertIncludes(source, '@toggle-recording="toggleRecording"')
assertIncludes(source, 'const observeOcrActive = ref(false)')
assertIncludes(source, 'const observeRecordingActive = ref(false)')
assertIncludes(source, ':stale-timeout-ms="store.videoStaleTimeoutMs"')
assertIncludes(source, 'store.captureResetToken')
assertIncludes(source, 'store.captureStatusInfo?.resources.browser_video_stream.running')
assertIncludes(source, 'resetLocalCaptureState(true)')
assertIncludes(source, 'observeSuppressDetachedRecording')
assertIncludes(source, "const usingCaptureCard = computed(() => store.inputMode === 'capture_card')")
assertIncludes(source, 'store.captureCardInfo?.running')
assertIncludes(source, 'store.nativeAudioInfo?.running')
assertIncludes(source, 'handleNativeAudioStopped')
assertIncludes(source, '音频接入已断开，语音识别已停止')
assertIncludes(source, 'const intervalMs = store.ocrIntervalMs')
assertIncludes(source, 'startOcr(intervalMs)')
assertIncludes(source, 'interval_ms: intervalMs')
assertNotIncludes(source, 'await store.startPhoneCaptureSession()')
assertNotIncludes(source, 'startOcr(1000)')
assertNotIncludes(source, 'interval_ms: 1000')

assertIncludes(yoloPanelSource, 'audio: false')
assertIncludes(yoloPanelSource, 'VIDEO_STALE_TIMEOUT_MS = 3000')
assertIncludes(yoloPanelSource, 'staleTimeoutMs?: number')
assertIncludes(yoloPanelSource, 'staleTimeoutMs.value')
assertIncludes(yoloPanelSource, 'handleVideoStreamStalled')
assertIncludes(yoloPanelSource, 'defineExpose({ startCapture, stopCapture, startOcr, stopOcr, startRecording, stopRecording })')
assertNotIncludes(yoloPanelSource, "emit('startStt')")
assertNotIncludes(yoloPanelSource, "emit('audioFrame'")
assertNotIncludes(yoloPanelSource, '@ffmpeg/ffmpeg')

assertIncludes(liveSourcePanelSource, 'audio: false')
assertNotIncludes(liveSourcePanelSource, 'audio: true')
assertNotIncludes(liveSourcePanelSource, "emit('audioFrame'")
assertNotIncludes(liveSourcePanelSource, 'createMediaStreamSource')

assertIncludes(statusBarSource, 'toggleProjection')
assertIncludes(statusBarSource, 'toggleVideo')
assertIncludes(statusBarSource, 'toggleAudio')
assertIncludes(statusBarSource, 'toggleStt')
assertIncludes(statusBarSource, 'toggleOcr')
assertIncludes(statusBarSource, 'toggleRecording')
assertIncludes(statusBarSource, '采集中...')
assertIncludes(statusBarSource, '停止采集')
assertIncludes(statusBarSource, 'CPU/GPU 初始化中...')
assertIncludes(statusBarSource, 'STT处理中')
assertIncludes(statusBarSource, 'OCR识别中')
assertIncludes(statusBarSource, 'ocrRuntimeLoading')
assertIncludes(statusBarSource, 'is-busy')
assertIncludes(statusBarSource, 'resource-toggle-spinner')
assertIncludes(statusBarSource, '音频接入')
assertIncludes(statusBarSource, '截图/OCR')
assertIncludes(statusBarSource, '录屏')

assertIncludes(storeSource, 'ocrIntervalMs: number')
assertIncludes(storeSource, 'setOcrIntervalMs(value: number)')
assertIncludes(storeSource, 'videoStaleTimeoutMs: number')
assertIncludes(storeSource, 'setVideoStaleTimeoutMs(value: number)')
assertIncludes(storeSource, 'sttRuntimeSettings: SttRuntimeSettings | null')
assertIncludes(storeSource, 'setSttRuntimeDevice(device: string)')
assertIncludes(storeSource, 'captureResetToken: number')
assertIncludes(settingsSource, '截图/OCR 频率')
assertIncludes(settingsSource, ':value="store.ocrIntervalMs"')
assertIncludes(settingsSource, '视频流检测')
assertIncludes(settingsSource, ':value="store.videoStaleTimeoutMs"')
assertIncludes(settingsSource, 'FunASR 运行设备')
assertIncludes(settingsSource, ':value="store.sttRuntimeSettings?.local_stt_device || \'cpu\'"')
assertIncludes(settingsSource, 'ADB：')
assertIncludes(settingsSource, 'online_count')

console.log('observationDashboard tests passed')
